// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ7Fes2kWgqzBCNM8Enxnduak8TcM4k8',
    appId: '1:1005348934748:web:50db48bb31fcb10e514299',
    messagingSenderId: '1005348934748',
    projectId: 'reddit-clone-372ab',
    authDomain: 'reddit-clone-372ab.firebaseapp.com',
    storageBucket: 'reddit-clone-372ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZ9dwrPPJRG0Xz_GTBM6G4itDpaKtGhc',
    appId: '1:1005348934748:android:1ec49b402c1fe520514299',
    messagingSenderId: '1005348934748',
    projectId: 'reddit-clone-372ab',
    storageBucket: 'reddit-clone-372ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BeFa3xuYDgzNYF2nmVgMRvCNLI0_TOU',
    appId: '1:1005348934748:ios:4330a1653c49861e514299',
    messagingSenderId: '1005348934748',
    projectId: 'reddit-clone-372ab',
    storageBucket: 'reddit-clone-372ab.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3BeFa3xuYDgzNYF2nmVgMRvCNLI0_TOU',
    appId: '1:1005348934748:ios:a6e548c86a650159514299',
    messagingSenderId: '1005348934748',
    projectId: 'reddit-clone-372ab',
    storageBucket: 'reddit-clone-372ab.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
